version: 2

project_name: lazygit-mcp-bridge

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: lazygit-mcp-bridge
    main: ./cmd/lazygit-mcp-bridge
    binary: lazygit-mcp-bridge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - docs/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: cappyzawa
    name: lazygit-mcp-bridge
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## lazygit-mcp-bridge {{.Tag}}
    
    Bridge between lazygit and AI assistants via Model Context Protocol (MCP).
    
    ### Installation
    
    ```bash
    # Install with Go
    go install github.com/cappyzawa/lazygit-mcp-bridge/cmd/lazygit-mcp-bridge@{{.Tag}}
    
    # Or download binary from releases
    ```
    
    ### What's Changed
  footer: |
    **Full Changelog**: https://github.com/cappyzawa/lazygit-mcp-bridge/compare/{{.PreviousTag}}...{{.Tag}}

# Homebrew tap (disabled until repository is created)
# brews:
#   - name: lazygit-mcp-bridge
#     repository:
#       owner: cappyzawa
#       name: homebrew-tap
#       branch: main
#     directory: Formula
#     homepage: "https://github.com/cappyzawa/lazygit-mcp-bridge"
#     description: "Bridge between lazygit and AI assistants via Model Context Protocol (MCP)"
#     license: "MIT"
#     test: |
#       system "#{bin}/lazygit-mcp-bridge --help"
#     install: |
#       bin.install "lazygit-mcp-bridge"